name: CPBuild

on:
  push:
    branches: [trunk]
  pull_request:
    branches: [trunk]

jobs:
  build:
    name: Build for ${{ matrix.os }}
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        name: [linux, windows]
        include:
          - name: linux
            os: ubuntu-latest
          - name: windows
            os: windows-latest

    steps:
      - uses: actions/checkout@v2
      - uses: symbitic/install-cmake@master

      - name: CMakePrep
        run: cmake -Bbuild .

      - name: Build
        run: cmake --build build
